# ============ Taps ============
tap "antoniorodr/memo"
tap "mobile-dev-inc/tap"
tap "supabase/tap"

# ============ CLI ============
brew "atuin"
brew "bat"
brew "btop"
brew "direnv"
brew "duf"
brew "dust"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "glab"
brew "gnupg"
brew "httpie"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "mise"
brew "neovim"
brew "pinentry-mac"
brew "ripgrep"
brew "starship"
brew "stow"
brew "swiftformat"
brew "tldr"
brew "watchman"
brew "yq"
brew "yt-dlp"
brew "zoxide"

# ============ Mobile ============
brew "apktool"
brew "cocoapods"
brew "ios-deploy"
brew "ios-webkit-debug-proxy"
brew "mobile-dev-inc/tap/maestro"

# ============ Backend ============
brew "supabase/tap/supabase"

# ============ Apps ============
cask "ghostty"
cask "zed"
cask "fork"
cask "spotify"
cask "zulu@17"

# ============ VS Code ============
vscode "aaron-bond.better-comments"
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "bwya77.islands-dark"
vscode "christopherstyles.html-entities"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "expo.vscode-expo-tools"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "foxundermoon.shell-format"
vscode "github.copilot-chat"
vscode "graphql.vscode-graphql-syntax"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "lokalise.i18n-ally"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-vscode-remote.remote-containers"
vscode "msjsdiag.vscode-react-native"
vscode "naumovs.color-highlight"
vscode "orta.vscode-jest"
vscode "oven.bun-vscode"
vscode "oxc.oxc-vscode"
vscode "redhat.vscode-yaml"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "swiftlang.swift-vscode"
vscode "swmansion.react-native-ide"
vscode "typescriptteam.native-preview"
vscode "unifiedjs.vscode-mdx"
vscode "vscode-icons-team.vscode-icons"
vscode "webpro.vscode-knip"
vscode "yoavbls.pretty-ts-errors"
